version: '3.5'
services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: nearbuzz
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express
        restart: always
        container_name: ashi_dev_mongo_express
        ports:
            - 9999:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
    mongodb_data_container: